name: 'Push a file to another repository'
description: 'Used for pushing a copy of a file to another repository'
inputs:
  source_files:
    description: 'Source files from the origin directory. Can have multiple space-separated sources.'
    required: true
  destination_repo:
    description: 'Destination repository'
    required: true
  # todo doesn't work
  # destination_folder:
  #   description: 'Directory to push the file to'
  #   required: false
  user_email:
    description: 'Email for the git commit'
    required: true
  user_name:
    description: 'GitHub username for the commit'
    required: true
  destination_branch:
    description: 'branch to push file to, defaults to main'
    required: false
  destination_branch_create:
    description: 'Destination branch to create for this commit'
    required: false
  commit_title:
    description: 'A custom message for the commit title. Defaults to "Update from ${GITHUB_REPOSITORY}"'
    required: false
  commit_description:
    description: 'A custom message for the commit description. Defaults to "Update from https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"'
    required: false
  # todo doesn't work
  # rename:
  #   description: 'Rename the destination file'
  #   required: false
  use_rsync:
    description: 'Copy files/directories using rsync instead of cp. Experimental feature, please know your use case'
    required: false
  git_server:
    description: 'Git server host, default github.com'
    required: false
    default: github.com
  push_with_force:
    description: "Use '--force' flag when pushing changes"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-file }}
    - ${{ inputs.destination-repo }}
    - ${{ inputs.destination-folder }}
    - ${{ inputs.user-email }}
    - ${{ inputs.destination-branch }}
    - ${{ inputs.destination-branch-create }}
    - ${{ inputs.commit-message }}
    - ${{ inputs.git-server }}
    - ${{ inputs.rename }}
    - ${{ inputs.use-rsync }}
    - ${{ inputs.push-with-force }}
branding:
  icon: 'git-commit'
  color: 'green'
