name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run shellcheck with reviewdog
        uses: reviewdog/action-shellcheck@v1.20.0
        with:
          level: style
          fail_on_error: true